# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
   inputs:
    hi:
     description: 'Say Hi'
     required: true
     default: ''
     
       
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can accessa
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell scrits
     

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: BorraVisalakshi/Workflow_calling
          event-type: my-event
     # client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
        id: event
         
          
      - name: Run a one-line script
        run: echo Hello, world!
        if: ${{steps.event.output == 'true'}}
        
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Repository Dispatch
          token: ${{ secrets.PAT }}
          inputs: '{ "hello":"${{ github.event.inputs.hi }}" }'
