# This is a basic workflow to help you get started with Actions

name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
   inputs:
    hello:
      description: 'Send for scan'
      required: true
      default: ''
    
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #  with:
      #    ref: ${{ github.event.client_payload.ref }}
    #  - run: echo ${{ github.event.client_payload.sha }}
# Controls when the action will run. 



      
